title: Brian Pardo 
logo: "/images/Screenshot_3.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Estudiante de Ingeniería Civil en Computación e Informática UCN
  <br><br>
  Me interesan las ideas diferentes, innovadoras y sorprendentes en mi área de estudio, 
  intentando que los alcances de la tecnología sean amplios e integren a la mayor cantidad de personas posibles.
  He tenido experiencia académica en ayudantías. Participo en la Academia de Programación Competitiva de la universidad, 
  donde hemos competido en los torneos Chileno-Argentino de Programación 2018 y 2019.
  <br><br>
  If you're going through hell, keep going.- Winston Churchill
  
  <a href="www.linkedin.com/in/brian-pardo-zambra-b618b21a4">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
